name: Deploy Homolog

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          install -m 700 -d ~/.ssh

          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -t ed25519 -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -vvv \
            -i ~/.ssh/id_ed25519 \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} exit

      - name: Deploy to homolog
        run: |
          echo "Iniciando deploy no host ${{ secrets.VM_HOST }}..."

          ssh \
            -i ~/.ssh/id_ed25519 \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
              set -e

              echo "Diretório atual: $(pwd)"

              cd /srv/expenses/homolog

              echo "Puxando alterações do branch homolog..."
              git pull origin homolog

              echo "Subindo containers com Docker Compose..."

              docker compose \
                -f docker-compose.yml \
                -f docker-compose.hml.yml \
                up -d --build

              echo "Deploy finalizado com sucesso!"
            EOF
