name: Deploy Produção

on:
  workflow_dispatch:

jobs:
  code-quality:
    uses: ./.github/workflows/eslint.yml

  # testes:
    
  merge-deploy:
    runs-on: self-hosted
    needs: [code-quality]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar bot Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge homolog na main
        run: |
          git checkout main
          git pull origin main
          git merge origin/homolog --no-ff -m "Deploy de homolog em prod"
          git push origin main

      - name: Deploy Produção
        run: |
          set -e

          cd /srv/expenses/prod

          git fetch origin
          git checkout main
          git pull origin main

          # Sobe os containers de produção
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

      - name: Notificar sucesso
        if: success()
        run: echo "Merge homolog -> main realizado e Deploy produção feito com sucesso"
 
      - name: Notificar falha
        if: failure()
        run: echo "Merge ou Deploy falhou"
